apiVersion: v1
entries:
  frontend:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-07-24T16:19:44.6033644+05:30"
    description: A Helm chart for Kubernetes
    digest: 8f6e5ed70d9b743af265d0bebc5507c5d4a5d166d0475ce7eae5ddf10b8b2b9b
    name: frontend
    type: application
    urls:
    - https://github.com/bansodesatish/helm-charts/charts/frontend/frontend-0.1.0.tgz
    version: 0.1.0
generated: "2024-07-24T16:19:44.593811+05:30"
